# Generated by Django 5.0.3 on 2024-12-09 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appApi', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wishlist',
            name='date',
        ),
    ]
